print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodTeacher                               |")
print("|    Name : Sophia                               |")
print("|    Version : 01                                |")
print(" ------------------------------------------------")
username = input("Teacher's name (try Mr Horan) ")
print(username + " is an ok teacher")