print(" ------------------------------------------------")
print("|                                                |")
print("|    03HelloWorld                                |")
print("|    Name : Sophia                               |")
print("|    Version : 01                                |")
print(" ------------------------------------------------")
print("Hello")
print("What is your name ? Sophia")
print("Goodbye Sophia")