print(" ------------------------------------------------")
print("|                                                |")
print("|    04GoodTeacher                               |")
print("|    Name : Sophia                               |")
print("|    Version : 01                                |")
print(" ------------------------------------------------")
print("Teacher's name (try Sophia)")