print(" ------------------------------------------------")
print("|                                                |")
print("|    07Menu                                      |")
print("|    Name : Sophia                               |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("")
print("1. Hello World")
print("2. Goodbye World")
print("3. Goodbye Person")
print("4. Good Teacher")
print("5. forLoop")
print("6. whileLoop")
print("7. string Loop")
print("8. Convert to ascii")
print("9. Encode a string")
print("x. To Exit")
y = input("Enter an option ")

if y == 1:
    print("")
    print("----Start of Output ---------------------------")
    print("")
    print("Hello World")
    print("")
    print("----End of Output -----------------------------")
    print("")
    print("")
    print("")
    input
elif y == 2:
    open('goodbyeworld.py')