print(" ------------------------------------------------")
print("|                                                |")
print("|    08StringLoop                                |")
print("|    Name : Sophia                               |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
y = input("What is your string? ")
for x in y:
    print(x)